dataset:
  num_classes: 21
  training:
    video_mp4_path: None
    video_info_path: thumos_annotations/val_video_info.csv
    video_anno_path: thumos_annotations/val_Annotation_ours.csv
    video_data_path: data/validation_flow_npy
    clip_length: 256
    clip_stride: 30
    crop_size: 96
  testing:
    video_mp4_path: None
    video_info_path: thumos_annotations/test_video_info.csv
    video_anno_path: thumos_annotations/test_Annotation_ours.csv
    video_data_path: data/test_flow_npy
    crop_size: 96
    clip_length: 256
    clip_stride: 128

model:
  in_channels: 2
  freeze_bn: true
  freeze_bn_affine: true
  backbone_model: backbones/flow_imagenet.pt
  layer_num: 2
  depth: 2

training:
  batch_size: 1
  learning_rate: 1e-5
  weight_decay: 1e-4
  max_epoch: 32
  focal_loss: true
  checkpoint_path: checkpoints/checkpoint_flow
  random_seed: 2133

testing:
  conf_thresh: 0.01
  top_k: 5000
  nms_thresh: 0.5
  nms_sigma: 0.5
  checkpoint_path: checkpoints/checkpoint_flow/checkpoint-12.ckpt
  output_path: ./output
  output_json: detection_results_flow.json